import { Auth } from "aws-amplify";
export const state = () => ({
  isAuthenticated: false,
  user: {},

  sentCode: null,
  confirmed: null
});

export const mutations = {
  setUser(state, user) {
    state.user = user;
  },

  isAuth(state, bool) {
    state.isAuthenticated = bool;
  },
  sentCode(state, bool) {
    state.sentCode = bool;
  }
};

export const actions = {
  async signIn({ commit }, { username, password }) {
    commit("setError", null, { root: true });
    try {
      const user = await Auth.signIn(username, password);
      console.log(user);
      commit("isAuth", true);
      commit("setUser", user);
      return user;
    } catch (error) {
      commit("setError", error, { root: true });
      console.log("error signing in", error);
      return error;
    }
  },
  async signOut() {
    console.log("ran");
    try {
      await Auth.signOut();
    } catch (error) {
      console.log("error signing out: ", error);
    }
  },
  async signUp({ commit }, { username, password }) {
    commit("setError", null, { root: true });
    console.log(username, password);
    try {
      const { user } = await Auth.signUp({
        username,
        password,
        attributes: {
          // email, // optional
          // phone_number, // optional - E.164 number convention
          // // other custom attributes
        }
      });
      user != null
        ? commit("setMessage", `Verification code sent to ${user.username}`, {
            root: true
          })
        : null;
      commit("setUser", user);
      console.log(user);
      commit("sentCode", true);
    } catch (error) {
      console.log("error signing up:", error);
      commit("setError", error, { root: true });
    }
  },
  async confirmSignUp({ commit }, { username, code }) {
    commit("setError", null);
    try {
      return await Auth.confirmSignUp(username, code);
    } catch (error) {
      commit("setError", error, { root: true });
      console.log("error confirming sign up", error);
    }
  },
  async reSendSignUp({ commit }, { username }) {
    commit("setError", null, { root: true });
    commit("setMessage", null, { root: true });
    console.log(username);
    try {
      const r = await Auth.resendSignUp(username);
      commit("setMessage", `Verification code sent`, { root: true });
      return r;
    } catch (error) {
      commit("setError", error, { root: true });
    }
  },
  async isAuthenticated({ commit }) {
    await Auth.currentAuthenticatedUser()
      .then(res => {
        commit("setUser", res);
        commit("isAuth", true);
      })
      .catch(() => {
        commit("isAuth", false);
      });
  }
};
